### ISSUE TITLE
Some questions on how to approach this issue.

### ISSUE THREAD

**Issue by Bancherd-DeLong** [KoichiYasuoka/spaCy-Thai#4]
Hi:

Nice work!  Did NOT mean to stalk you, but I came across  this github; and it is very much related to what I need, to get things done.

I am working on(more like trying to learn about) knowledge graphs, with application to Thai language.  At the moment, I am trying to collect data using this particular form:

Node-1 -----relation---- Node-2

Let's say that I have: "แผนกนี้กำลังเผชิญกับความท้าทาย"

I would like "แผนก" ---"เผชิญ"---"ความท้าทาย" instead of "แผนก" ---"เผชิญ"---"ความ" --"ท้าทาย"  as it currently does.

Is this caused by the tokenizer used?
IF I were to include "ความท้าทาย" in the dictionary, so that it segments the way I want.  Would I still have to retrain things before spacy-thai recognizes "ความท้าทาย" as NOUN?

Thanks.

**Comment by KoichiYasuoka** [comment]
Hi @Bancherd-DeLong 

>Is this caused by the tokenizer used?

Yes, it's because spaCy uses [pyThaiNLP](https://pythainlp.github.io/) for Thai tokenization:

```
>>> from pythainlp import word_tokenize,pos_tag
>>> nlp=lambda txt:pos_tag(word_tokenize(txt))
>>> doc=nlp("แผนกนี้กำลังเผชิญกับความท้าทาย")
>>> print(doc)
[('แผนก', 'NCMN'), ('นี้', 'DDAC'), ('กำลัง', 'XVBM'), ('เผชิญ', 'VSTA'), ('กับ', 'RPRE'), ('ความ', 'FIXN'), ('ท้าทาย', 'VSTA')]
```

And pyThaiNLP separates ''ความท้าทาย'' into two words. So as spaCy-Thai.

**Comment by KoichiYasuoka** [comment]
I know [roberta-base-thai-syllable-upos](https://huggingface.co/KoichiYasuoka/roberta-base-thai-syllable-upos) tokenizes another way:

```
>>> from transformers import AutoTokenizer,AutoModelForTokenClassification,TokenClassificationPipeline
>>> brt="KoichiYasuoka/roberta-base-thai-syllable-upos"
>>> tkz=AutoTokenizer.from_pretrained(brt)
>>> mdl=AutoModelForTokenClassification.from_pretrained(brt)
>>> nlp=TokenClassificationPipeline(model=mdl,tokenizer=tkz,aggregation_strategy="simple")
>>> doc=nlp("แผนกนี้กำลังเผชิญกับความท้าทาย")
>>> print(doc)
[{'entity_group': 'NOUN', 'score': 0.9744798, 'word': 'แผนก', 'start': 0, 'end': 4}, {'entity_group': 'DET', 'score': 0.9853287, 'word': 'นี้', 'start': 4, 'end': 7}, {'entity_group': 'PART', 'score': 0.7498409, 'word': 'กำลัง', 'start': 7, 'end': 12}, {'entity_group': 'VERB', 'score': 0.97723466, 'word': 'เผชิญ', 'start': 12, 'end': 17}, {'entity_group': 'ADP', 'score': 0.97113955, 'word': 'กับ', 'start': 17, 'end': 20}, {'entity_group': 'VERB', 'score': 0.94858295, 'word': 'ความท้าทาย', 'start': 20, 'end': 30}]
```

The result of roberta-base-thai-syllable-upos seems what you want. But I'm vague how to use RoBERTa model as a spaCy tokenizer.

**Comment by Bancherd-DeLong** [comment]
Thank you for the suggestion.  I tried your suggestion, and it  has strengths and weakness inherent in syllable-based approaches., 

Looks like  dict-based approach, in combination with some hard-coded rules, is the best approach to segmenting Thai words.  I wish we could have a good segmenter, it would make life a lot easier.
