### ISSUE TITLE
New Dataset! Thai Universal Dependency Treebank

### ISSUE THREAD

**Issue by wannaphong** [KoichiYasuoka/spaCy-Thai#6]
Hello! Chulalongkorn University release Thai Universal Dependency Treebank, consisting of 3,627 trees annotated in accordance with the Universal Dependencies (UD) framework. I think you may don't has multiple root issue in the dataset like #5.

arXiv: https://arxiv.org/abs/2405.07586
GitHub (dataset and model): https://github.com/nlp-chula/TUD

**Comment by KoichiYasuoka** [comment]
Thank you @wannaphong and I've just released `spaCy-Thai` 0.7.4, which is trained by Thai Universal Dependency Treebank, changing `ADJ` into `VERB`. I will also train `esupar` Thai models later.

**Comment by wannaphong** [comment]
Thank you!
