### ISSUE TITLE
`t.lemma_` is not shown

### ISSUE THREAD

**Issue by lamrongol** [KoichiYasuoka/spaCy-Thai#7]
I have run sample code and found `t.lemma_` is not shown
```
1	แผนก		NOUN	NCMN	_	4	nsubj	_	SpaceAfter=No
2	นี้		DET	DDAC	_	1	det	_	SpaceAfter=No
3	กำลัง		AUX	XVBM	_	4	aux	_	SpaceAfter=No
4	เผชิญ		VERB	VSTA	_	0	ROOT	_	SpaceAfter=No
5	กับ		ADP	RPRE	_	6	case	_	SpaceAfter=No
6	ความ		PART	FIXN	_	4	obl	_	SpaceAfter=No
7	ท้าทาย		VERB	VACT	_	6	acl	_	SpaceAfter=No
8	ใหม่		ADV	ADVN	_	7	advmod	_	SpaceAfter=No
```

Other(e.g. POS) are same with sample but only `t.lemma_` is empty.

**Comment by KoichiYasuoka** [comment]
Sorry but it was my mistake to support spaCy V3. Now I've fixed the bug, so please use the newer version (0.7.7) of spaCy-Thai.

**Comment by lamrongol** [comment]
I confirmed this is resolved, thank you.
