### ISSUE TITLE
`OverflowError: Python integer -1 out of bounds for uint64` error occurs

### ISSUE THREAD

**Issue by lamrongol** [KoichiYasuoka/spaCy-Thai#8]
I don't remember clearly but after upgraded Python to `3.13`( which spacy doesn't work ) and downgraded to `3.12`, I encountered following error(directory is replaced to "< My Workspace >" and running sample code on "spaCy_th.py"):
```
  File "<My Workspace>\spaCy_th.py", line 14, in main
    doc = nlp("แผนกนี้กำลังเผชิญกับความท้าทายใหม่")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<My Workspace>\.idea\.env\Lib\site-packages\spacy\language.py", line 1057, in __call__
    error_handler(name, proc, [doc], e)
  File "<My Workspace>\.idea\.env\Lib\site-packages\spacy\util.py", line 1722, in raise_error
    raise e
  File "<My Workspace>\.idea\.env\Lib\site-packages\spacy\language.py", line 1052, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<My Workspace>\.idea\.env\Lib\site-packages\spacy_thai\spacy_thai.py", line 70, in __call__
    a=numpy.array(list(zip(deps,heads)),dtype="uint64")
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: Python integer -1 out of bounds for uint64
```

Regards,

**Comment by KoichiYasuoka** [comment]
Sorry @lamrongol but your environment seems Windows 10/11 which I could not support directly. Please use WSL (Windows Subsystem Linux) or Cygwin.

**Comment by jad-bey** [comment]
I'm not too familiar with this project, but could this error be due to the `heads` variable from line 68 having a negative number when it is zipped to the NumPy array? I don't know if `int(head)-int(id)` can ever be negative, but it could stem from `s` on line 52 resulting in negative values and then later causing the uint64 error when creating the NP array.

**Comment by KoichiYasuoka** [comment]
Maybe yes @jadb18 but numpy version 1.x could handle negative numbers on `uint64`

```
>>> import numpy
>>> numpy.array([-1],dtype="uint64")
array([18446744073709551615], dtype=uint64)
```

while numpy version 2.x cannot.

**Comment by KoichiYasuoka** [comment]
I've just released spaCy-Thai v0.7.8 with a quick hack for numpy v2.x. But I'm vague that this causes another error. Thank you @jadb18 @lamrongol

**Comment by lamrongol** [comment]
I confirmed error is resolved, thank you.

**Comment by jad-bey** [comment]
Thank you for the fix! I have also had similar errors with indexing on Mac and WSL with C arrays and `uint` in the past, but I will keep the NP version 2 changes in mind.
